# Generated by Django 3.2.8 on 2021-10-28 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0003_alter_auction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='categori',
        ),
        migrations.AddField(
            model_name='auction',
            name='categori',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.Categori'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
