# Generated by Django 3.2.8 on 2021-10-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211028_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='createdate',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
