# Generated by Django 3.2.8 on 2021-10-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auctions.status'),
        ),
    ]
