# Generated by Django 3.2.8 on 2021-10-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.status'),
        ),
    ]
