# Generated by Django 3.2.8 on 2021-11-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
