# Generated by Django 3.2.8 on 2021-11-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_rates_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='last_rate',
            field=models.FloatField(default=0),
        ),
    ]
