# Generated by Django 3.2.8 on 2021-11-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20211101_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.IntegerField(null=True),
        ),
    ]
