# Generated by Django 3.2.8 on 2021-11-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20211101_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionwinner',
            old_name='last_rate',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='auctionwinner',
            name='date',
            field=models.DateTimeField(auto_now_add=True, blank=True),
            preserve_default=False,
        ),
    ]
